Repository redhat-developer/app-services-guides, pull requests merged in 2021-09, with the labels that each got.

#285 Updating Instance name to Name
  getting-started/README.adoc
Labels: tech-verified, doc-verified

#292 chore: remove invalid env variable
  quarkus/README.adoc
Labels: tech-verified, priority/critical

#294 docs: scripts and kafkacat quickstarts updates
  getting-started/README.adoc
  kafka-bin-scripts/README.adoc
  kafka-bin-scripts/quickstart.yml
  kafkacat/README.adoc
  kafkacat/quickstart.yml
Labels: documentation

#300 docs: delete and reset updates for consumer groups
  consumer-configuration/README.adoc
Labels: documentation
