Repository redhat-developer/app-services-guides, pull requests merged in 2022-04, with the labels that each got.

#443 JC-587 copyedit of connectors quickstart
  docs/connectors/getting-started-connectors/README.adoc
  docs/connectors/getting-started-connectors/images/connectors-diagram.png
  docs/connectors/getting-started-connectors/quickstart.yml
Labels: documentation

#447 Fix grafana step
  docs/kafka/metrics-monitoring-kafka/README.adoc
Labels: under review

#485 fix: issues with kcat guide
  docs/kafka/kcat-kafka/README.adoc
Labels: summit
